### ISSUE TITLE
proofreading suggestions 

### ISSUE THREAD

**Issue by yina-quique** [rbcavanaugh/csd-stats#2]
About
This is a repository for resources related to learning and doing statistics, data analysis, open science, using R, and other important things. These resources have been curated for (but certainly not limited to) new and seasoned researchers in the field of Communication Sciences and Disorders.

Before you get bogged down in this overwhelming list of resources, I suggest you entertain yourself with this highly enjoyable scientific article (or at least listen to it during your commute this week; the authors narrate an audio version) and remember that your goal is to do science, and these are just tools you might find helpful along the way.
[Things Could Be Better by Adam Mastroianni](https://www.experimental-history.com/p/things-could-be-better)
These resources are generally based around the statistical programming language R, mainly because it's what I was trained in, what I know the most about, and the scripted language used most often in CSD research. Python is cool too, sometimes. I wish I knew Julia.
(But if you asked me which additional language I thought researchers might find useful on top of R…it would probably be SQL…unless you're thinking about an alt-ac career, in which case it would definitely be Python…and SQL. But really, once you know one of these fairly well, it's easy enough to pick up the others. Also, you should probably learn some very basic git.)
Anyway, the point is that this list is for R, but it's not an exclusive endorsement of R. Perhaps someone will add a section for Python and Julia. If you really don't want to learn a scripted/statistical language like R (or Python, Julia, SQL…), then I suggest you go check out [JASP](https://jasp-stats.org/), which is a free and open-source GUI built on top of R.

Getting started
I recommend that you use this list of resources in a very ad-hoc fashion. Some of the sections I have ordered so that the resource I recommend most is at the top (indicated with an asterisk). Others are lists of resources or people I have learned a great deal from and think you might find helpful. But if they’re on this list, then I have found them helpful, at least minimally, at some point or another.
If you don’t see what you’re looking for, please consider asking for suggestions or recommendations on the [discussions page](https://github.com/rbcavanaugh/csd-stats/discussions) (Yes, you will have to make a GitHub account. It’s free. Students get [extra perks](https://education.github.com/pack), and [so do faculty](https://education.github.com/discount_requests/application)).

Contributing
Please contribute!! Here's how:
Go open an issue in the [GitHub repository](https://github.com/rbcavanaugh/csd-stats) (the "issues" tab) and include three things:
a link or reference
which section it belongs in
and how you found it useful
If any links are broken or out of date, the GitHub issues are a good place to let me know so I can fix them or delete the resource.

Contributors:
Your name could be here!

A word of advice
Learning R or any of the stats below, especially for anyone who has never written code before, can be daunting. But it is a skill that is worth learning. The best way to learn R is to use it. The best way to use it is to have a project for which you need to use it. The resources below are fantastic - but I highly suggest you use them in tandem with a project you are highly motivated to do in R. For example, you do a few chapters or sections of one of these resources, and then you go try to apply that knowledge in your project and with your data.

Disclosure: Github co-pilot wrote most of this section, and I think it's pretty spot on. Based on how I understand LLMs to work, this is probably the most common advice for learning R, programming languages, or whatever the internet is saying about learning these days.
Also, having a mentor who knows a little more R or stats than you is helpful, even if only to check in with you occasionally or give yourself some external accountability. If you don't have that person, then it's worth spending the time and effort to find them (small plug for ASHA's [MARC](https://www.asha.org/students/mentoring/marc/) program, which I have benefited greatly from, and the many mentors who have and continue to help me learn).

A word of caution
I have not proofread this page closely, and you have probably realized by now that it's full of run-on sentences, inconsistent punctuation, and other errors.

**Comment by rbcavanaugh** [comment]
thanks Yina!
