### ISSUE TITLE
Add R for Reproducible Scientific Analysis to CSD-stats

### ISSUE THREAD

**Issue by courtjewell** [rbcavanaugh/csd-stats#5]
**R for Reproducible Scientific Analysis by Software Carpentry** 

Link: https://swcarpentry.github.io/r-novice-gapminder/index.html

**What section it belongs to (or propose a new one!)**

Learning R

**How you found it useful**

Step-by-step guide on introducing R and R-studio with the basic fundamentals. The information is pretty replicable to tutorials found in R for Data Science, but I found it slightly more approachable for novices. Feel free to add if you think it could be a good contribution!

**Whether you would like to be acknowledged as a contributor**

Sure! If the resource is worthy enough!

**Comment by rbcavanaugh** [comment]
Added! Thank you!
